config/routes.rb
Rails.application.routes.draw do
  resources :vendors, except: %i(show)

  resources :adapters, except: %i(index)

  root 'adapters#index'
end

app/models/adapter.rb
class Adapter < ApplicationRecord
  belongs_to :vendor
  belongs_to :adapter_type
  belongs_to :connection_type

  validates :name, presence: true, length: { minimum: 5 }
  validates :vendor_id, presence: true
  validates :adapter_type_id, presence: true
  validates :connection_type_id, presence: true

  scope :categorize, lambda { |vendor_id, adapter_type_id, connection_type_id|
    adapters = Adapter.all.includes(:vendor, :adapter_type, :connection_type)
    if vendor_id || adapter_type_id || connection_type_id
      search_params = { vendor_id: vendor_id,
                        adapter_type_id: adapter_type_id,
                        connection_type_id: connection_type_id }
                      .reject { |_key, val| val.blank? }

      adapters = adapters.where search_params
    end

    adapters.order(created_at: :desc)
  }
end

app/models/adapter_type.rb
class AdapterType < ApplicationRecord
  has_many :adapters, dependent: :destroy

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/connection_type.rb
class ConnectionType < ApplicationRecord
  has_many :adapters, dependent: :destroy

  validates :name, presence: true
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :adapters, dependent: :destroy

  validates :name, presence: true
end

app/controllers/adapters_controller.rb
class AdaptersController < ApplicationController
  before_action :set_adapter!, only: %i(edit update destroy show)

  def index
    @pagy, @adapters = pagy(Adapter
                            .categorize(params[:vendor_id], params[:adapter_type_id], params[:connection_type_id]),
                            page: adapter_restore_page)

    remember_page
  end

  def new
    @adapter = Adapter.new
  end

  def create
    @adapter = Adapter.new adapter_params

    if @adapter.save
      flash[:success] = 'Adapter added!'
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    remember_action
  end

  def update
    if @adapter.update adapter_params
      flash[:success] = 'Adapter updated!'
      redirect_to adapter_path(@adapter)
    else
      render :edit
    end
  end

  def destroy
    @adapter.destroy
    flash[:success] = 'Adapter deleted!'
    redirect_to root_path
  end

  def show
    remember_action
  end

  private

  def adapter_params
    params.require(:adapter).permit(:name, :vendor_id, :adapter_type_id, :connection_type_id)
  end

  def set_adapter!
    @adapter = Adapter.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandling
  include Pagy::Backend
  include Pagination
end

app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound(exception)
      logger.warn exception
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/concerns/pagination.rb
module Pagination
  extend ActiveSupport::Concern

  included do
    private

    def remember_page
      return unless params[:page]

      session[:page] = params[:page]
    end

    def restore_page
      return unless session[:page]

      session.delete(:page)
    end

    def remember_action
      session[:last_action] = action_name
    end

    def adapter_restore_page
      return unless session[:last_action]
      return unless %w(show edit).include?(session[:last_action])

      session.delete(:last_action)

      return unless session[:page]

      session[:page]
    end
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor!, only: %i(edit update destroy)
  before_action :fetch_vendors!, only: %i(index new)

  def index
    @vendor ||= Vendor.new

    remember_page
  end

  def new
    @vendor = Vendor.new
    render 'index'
  end

  def create
    @vendor = Vendor.new vendor_params

    if @vendor.save
      flash[:success] = 'Vendor added!'
      redirect_to vendors_path
    else
      render :new
    end
  end

  def edit
    @pagy, @vendors = pagy Vendor.order(created_at: :desc), page: restore_page

    remember_page

    render 'index'
  end

  def update
    if @vendor.update vendor_params
      flash[:success] = 'Vendor updated!'
      redirect_to vendors_path
    else
      render :edit
    end
  end

  def destroy
    @vendor.destroy
    flash[:success] = 'Vendor deleted!'
    redirect_to vendors_path
  end

  private

  def vendor_params
    params.require(:vendor).permit(:name)
  end

  def set_vendor!
    @vendor = Vendor.find params[:id]
  end

  def fetch_vendors!
    @pagy, @vendors = pagy Vendor.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def pagination(obj)
    raw(pagy_bootstrap_nav(obj)) if obj.pages > 1
  end
end

app/views/adapters/_adapter.html.haml
.col-sm-12.col-md-6.col-lg-4
  %article.card.border-0.my-4.shadow{id: "#{dom_id adapter}"}
    .card-body
      %h4.card-title.mb-4.text-truncate= adapter.name

      %section.card-text
        %p= adapter.vendor.name
        %p= adapter.adapter_type.name
        %p= adapter.connection_type.name

      .container
        .row.justify-content-center
          .col-auto
            = link_to 'Show', adapter_path(adapter), class: 'btn btn-outline-primary'
          .col-auto
            = link_to 'Edit', edit_adapter_path(adapter), class: 'btn btn-outline-secondary'
          .col-auto
            = link_to 'Destroy', adapter_path(adapter), class: 'btn btn-outline-danger',
              data: {method: :delete, confirm: "Are you sure?"}

app/views/adapters/_form.html.haml
= render 'shared/errors', object: @adapter

= form_with model: @adapter do |f|
  
  .mb-3.form-group
    = f.label :name, class: 'mb-1'
    = f.text_area :name, placeholder: "Name", class: 'form-control'

  .mb-3.form-group
    = f.label :vendor_id, class: 'mb-1'
    = f.collection_select :vendor_id, Vendor.all, :id, :name,
      {}, class: 'form-control'

  .mb-3.form-group
    = f.label :adapter_type_id, class: 'mb-1'
    = f.collection_select :adapter_type_id, AdapterType.all, :id, :name,
      {}, class: 'form-control'

  .mb-3.form-group
    = f.label :connection_type_id, class: 'mb-1'
    = f.collection_select :connection_type_id, ConnectionType.all, :id, :name,
      {}, class: 'form-control'

  .container.mt-5
    .row.justify-content-center
      .col-auto
        = f.submit "#{btn_val}", class: 'btn btn-outline-primary'
      .col-auto
        = link_to 'Home', root_path, class: 'btn btn-outline-secondary'

app/views/adapters/edit.html.haml
.text-center
  %h1.display-5.text-secondary.mb-5 Edit adapter

.container
  .row.justify-content-around
    .col-sm-10.col-md-6
      = render 'form', btn_val: "Update"

app/views/adapters/index.html.haml
.container.text-center
  %h1.display-5.text-secondary.mb-5 Adapters

.container.mb-4
  = link_to 'Categories', '#categories_form',
    class: 'btn btn-outline-primary mb-3', data: {'bs-toggle': 'collapse'}

  = tag.div class: 'collapse', id: 'categories_form' do

    = form_with url: root_path, method: :get do |f|
      .mb-3.form-group
        = f.label :vendor_id, class: 'mb-1'
        = f.collection_select :vendor_id, Vendor.all, :id, :name,
          {include_blank: true}, class: 'form-control'

      .mb-3.form-group
        = f.label :adapter_type_id, class: 'mb-1'
        = f.collection_select :adapter_type_id, AdapterType.all, :id, :name,
          {include_blank: true}, class: 'form-control'

      .mb-3.form-group
        = f.label :connection_type_id, class: 'mb-1'
        = f.collection_select :connection_type_id, ConnectionType.all, :id, :name,
          {include_blank: true}, class: 'form-control'

      .form-group
        = f.submit 'Search', class: 'btn btn-outline-primary'
        = link_to 'All', root_path, class: 'btn btn-outline-secondary'

.container
  = pagination(@pagy)
    
.container-xl
  .row.justify-content-center
    = render @adapters

.container.mt-3
  = pagination(@pagy)

app/views/adapters/new.html.haml
.text-center
  %h1.display-5.text-secondary.mb-5 Add new adapter

.row.justify-content-around
  .col-auto
    = render 'form', btn_val: "Add"

app/views/adapters/show.html.haml
.text-center
  %h1.display-5.text-secondary.mb-5 More details

  %h4.mb-4= @adapter.name
  
.d-flex.justify-content-around
  .d-inline-block
    %p.h5= @adapter.vendor.name
    %p.h5= @adapter.adapter_type.name
    %p.h5= @adapter.connection_type.name
    
.text-center.mt-4
  = link_to 'Home', root_path, class: 'btn btn-outline-primary'
  = link_to 'Edit', edit_adapter_path(@adapter), class: 'btn btn-outline-secondary'
  = link_to 'Destroy', adapter_path(@adapter), class: 'btn btn-outline-danger',
    data: {method: :delete, confirm: "Are you sure?"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title NetworkingEquipment
    %meta{name: "viewport", content: "device-width,initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true

    %body.bg-light
      %header
        -# navbar
        %nav.navbar.navbar-expand-md.navbar-light.bg-white
          .container-xxl
            = link_to 'NetworkingEquipment', root_path, class: 'nav-link text-primary display-6'
            
            -# toggle button
            %button.navbar-toggler{type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#main-nav", "aria-controls": "main-nav", "aria-expanded": "false", "aria-label": "Toggle navigation"}
              %span.navbar-toggler-icon

            -# navbar links
            .collapse.navbar-collapse.justify-content-end.align-center#main-nav
              %ul.navbar-nav
                %li.nav-item
                  = link_to 'Vendors', vendors_path, class: 'nav-link text-white btn btn-secondary'
                %li.nav-item
                  = link_to 'New adapter', new_adapter_path, class: 'nav-link text-white btn btn-secondary ms-md-3'

      %main.py-4.my-3
        - flash.each do |k, v|
          = tag.div v, class: "container alert alert-#{k}", role: 'alert'
        
        = yield

      %footer.p-4.bg-white
        .container.text-center
          &copy;
          = "Copyright #{Time.now.year} Networking Equipment"

app/views/shared/_errors.html.haml
- if object.errors.full_messages.any?
  .alert.alert-danger
    %ul.mb-0
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/vendors/_form.html.haml
= render 'shared/errors', object: @vendor

= form_with model: [ @vendor ] do | f |
  
  .mb-3.form-group
    = f.label :name, class: 'mb-1'

    = f.text_area :name, class: 'form-control'

  - if action_name == 'edit'
    .container.row.justify-content-center
      .col-auto
        = f.submit 'Update', class: 'btn btn-outline-primary'
      .col-auto
        = link_to 'New', new_vendor_path, class: 'btn btn-outline-secondary'
  - else
    = f.submit 'Add', class: 'btn btn-outline-primary'

app/views/vendors/_vendor.html.haml
%tr
  %td
    = vendor.name
  %td
    = link_to 'Edit', edit_vendor_path(vendor), class: 'btn btn-sm btn-outline-secondary'
    = link_to 'Delete', vendor_path(vendor), class: 'btn btn-sm btn-outline-danger',
      data: {method: :delete, confirm: "Are you sure?"}

app/views/vendors/index.html.haml
.container.text-center
  %h1.display-5.text-secondary.mb-5 Vendors

.container
  = pagination @pagy

.container-xl.my-4
  .row.justify-content-center.g-5

    .col-sm-12.col-md-auto
      %table.table.mx-auto
        %tr
          %th Name
          %th Actions
        = render @vendors
        
    .col-sm-6.col-md-4.text-center.my-md-auto
      %article.card.border-0.shadow.py-3
        .card-body
          = render 'form'
            
.container
  = pagination @pagy